sudo: required
language: java
jdk:
  - openjdk8

before_install:
  - cd libs && wget http://www.arrestedcomputing.com/readability/readability.jar?attredirects=0 && cd ..
  - cd libs && wget https://dibt.unimol.it/report/readability/files/readability.zip && unzip readability.zip && cd ..
  - cp libs/readability.classifier ./

script:
  - ./gradlew clean test

after_success:
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file: "plugin_packaging/readabilitySHARK_plugin.tar"
    skip_cleanup: true
    on:
      repo: smartshark/readabilitySHARK
      tags: true