sudo: required
language: java
jdk:
  - openjdk8

cache:
  directories: libs

install: skip

before_script:
  - if [ ! -f libs/readability.jar ]; then cd libs && wget -O readability.jar http://www.arrestedcomputing.com/readability/readability.jar?attredirects=0 && cd ..; fi
  - if [ ! -f libs/readability.zip ]; then cd libs && wget https://dibt.unimol.it/report/readability/files/readability.zip && unzip -o readability.zip && cd ..; fi
  - cp libs/readability.classifier ./

script:
  - ./gradlew clean test

after_success:
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file: "plugin_packaging/readabilitySHARK_plugin.tar"
    skip_cleanup: true
    on:
      repo: smartshark/readabilitySHARK
      tags: true