sudo: required
language: java
jdk:
  - openjdk8

script:
  - ./gradlew clean test

after_success:
  - cd plugin_packaging && ./build_plugin.sh && cd ..

deploy:
  - provider: releases
    api_key: ${GH_TOKEN}
    file: "plugin_packaging/readabilitySHARK_plugin.tar"
    skip_cleanup: true
    on:
      repo: smartshark/readabilitySHARK
      tags: true